// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7UDwdxOL4bzcM17aXYWU5G0shJMU9vwI',
    appId: '1:1058882245587:web:282c38a139cadc15c05526',
    messagingSenderId: '1058882245587',
    projectId: 'tailormaster12',
    authDomain: 'tailormaster12.firebaseapp.com',
    databaseURL: 'https://tailormaster12-default-rtdb.firebaseio.com',
    storageBucket: 'tailormaster12.firebasestorage.app',
    measurementId: 'G-HJN512J2MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9DWAAERGvX-uHRXbKsEN9jP09NmWoSTU',
    appId: '1:1058882245587:android:05bc12b5270ff841c05526',
    messagingSenderId: '1058882245587',
    projectId: 'tailormaster12',
    databaseURL: 'https://tailormaster12-default-rtdb.firebaseio.com',
    storageBucket: 'tailormaster12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvLE8-3loOK3nHHn3ahhdci43TV_Dok0Q',
    appId: '1:1058882245587:ios:8f8869b23517128ec05526',
    messagingSenderId: '1058882245587',
    projectId: 'tailormaster12',
    databaseURL: 'https://tailormaster12-default-rtdb.firebaseio.com',
    storageBucket: 'tailormaster12.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvLE8-3loOK3nHHn3ahhdci43TV_Dok0Q',
    appId: '1:1058882245587:ios:8f8869b23517128ec05526',
    messagingSenderId: '1058882245587',
    projectId: 'tailormaster12',
    databaseURL: 'https://tailormaster12-default-rtdb.firebaseio.com',
    storageBucket: 'tailormaster12.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7UDwdxOL4bzcM17aXYWU5G0shJMU9vwI',
    appId: '1:1058882245587:web:eae6089799f02549c05526',
    messagingSenderId: '1058882245587',
    projectId: 'tailormaster12',
    authDomain: 'tailormaster12.firebaseapp.com',
    databaseURL: 'https://tailormaster12-default-rtdb.firebaseio.com',
    storageBucket: 'tailormaster12.firebasestorage.app',
    measurementId: 'G-VJ1XQ50BPH',
  );
}
